version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: 'mongodb'
    ports:
      - 27017:27017
    networks:
      - mynet

  backend:    
      restart: always
      build:
        context: ./
      volumes:
        - .:/src
      depends_on:
        - mongodb
      environment:
        PORT: 3002
        MONGO_URL: mongodb://mongodb:27017/mydb
        ACCESS_TOKEN_SECRET: tokenjwtlalalal
      ports:
          - 3002:3002
      networks:
        - mynet

networks:
  mynet:
    driver: bridge  